/*
 * Wallet-Pay API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.walletpay.internal.api;

import io.openweb3.walletpay.internal.ApiException;
import io.openweb3.walletpay.models.RefundIn;
import io.openweb3.walletpay.models.ResponseError;
import io.openweb3.walletpay.models.ResponseListRefundOut;
import io.openweb3.walletpay.models.ResponseRefundOut;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RefundApi
 */
@Ignore
public class RefundApiTest {

    private final RefundApi api = new RefundApi();

    
    /**
     * List Refunds
     *
     * List refunds.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1RefundListTest() throws ApiException {
        String appId = null;
        Integer size = null;
        Integer page = null;
        String orderId = null;
        ResponseListRefundOut response = api.v1RefundList(appId, size, page, orderId);

        // TODO: test validations
    }
    
    /**
     * Create Refund
     *
     * Create a refunds.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1RefundsCreateTest() throws ApiException {
        String appId = null;
        RefundIn refundIn = null;
        ResponseRefundOut response = api.v1RefundCreate(appId, refundIn);

        // TODO: test validations
    }
    
}
