/*
 * Wallet-Pay API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.walletpay.internal.api;

import io.openweb3.walletpay.internal.ApiException;
import io.openweb3.walletpay.models.EndpointIn;
import io.openweb3.walletpay.models.EndpointOut;
import io.openweb3.walletpay.models.HttpErrorOut;
import io.openweb3.walletpay.models.ListResponseEndpointOut;
import io.openweb3.walletpay.models.Ordering;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WebhookEndpointApi
 */
@Ignore
public class WebhookEndpointApiTest {

    private final WebhookEndpointApi api = new WebhookEndpointApi();

    
    /**
     * Create endpoint
     *
     * Create a webhook endpoint.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1EndpointCreateTest() throws ApiException {
        EndpointIn endpointIn = null;
        EndpointOut response = api.v1EndpointCreate(endpointIn);

        // TODO: test validations
    }
    
    /**
     * Delete endpoint
     *
     * delete the specified webhook endpoint.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1EndpointDeleteTest() throws ApiException {
        String endpointId = null;
        EndpointOut response = api.v1EndpointDelete(endpointId);

        // TODO: test validations
    }
    
    /**
     * List endpoints
     *
     * List endpoints.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void v1EndpointListTest() throws ApiException {
        Integer limit = null;
        String cursor = null;
        Ordering order = null;
        ListResponseEndpointOut response = api.v1EndpointList(limit, cursor, order);

        // TODO: test validations
    }
    
}
