/*
 * Wallet-Pay API Documentations
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ResponseOrderOut struct for ResponseOrderOut
type ResponseOrderOut struct {
	Data OrderOut `json:"data"`
}

// NewResponseOrderOut instantiates a new ResponseOrderOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseOrderOut(data OrderOut) *ResponseOrderOut {
	this := ResponseOrderOut{}
	this.Data = data
	return &this
}

// NewResponseOrderOutWithDefaults instantiates a new ResponseOrderOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseOrderOutWithDefaults() *ResponseOrderOut {
	this := ResponseOrderOut{}
	return &this
}

// GetData returns the Data field value
func (o *ResponseOrderOut) GetData() OrderOut {
	if o == nil {
		var ret OrderOut
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResponseOrderOut) GetDataOk() (*OrderOut, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ResponseOrderOut) SetData(v OrderOut) {
	o.Data = v
}

func (o ResponseOrderOut) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableResponseOrderOut struct {
	value *ResponseOrderOut
	isSet bool
}

func (v NullableResponseOrderOut) Get() *ResponseOrderOut {
	return v.value
}

func (v *NullableResponseOrderOut) Set(val *ResponseOrderOut) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseOrderOut) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseOrderOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseOrderOut(val *ResponseOrderOut) *NullableResponseOrderOut {
	return &NullableResponseOrderOut{value: val, isSet: true}
}

func (v NullableResponseOrderOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseOrderOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


