/*
 * Wallet-Pay API Documentations
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ResponseEndpointOut struct for ResponseEndpointOut
type ResponseEndpointOut struct {
	Data EndpointOut `json:"data"`
}

// NewResponseEndpointOut instantiates a new ResponseEndpointOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseEndpointOut(data EndpointOut) *ResponseEndpointOut {
	this := ResponseEndpointOut{}
	this.Data = data
	return &this
}

// NewResponseEndpointOutWithDefaults instantiates a new ResponseEndpointOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseEndpointOutWithDefaults() *ResponseEndpointOut {
	this := ResponseEndpointOut{}
	return &this
}

// GetData returns the Data field value
func (o *ResponseEndpointOut) GetData() EndpointOut {
	if o == nil {
		var ret EndpointOut
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResponseEndpointOut) GetDataOk() (*EndpointOut, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ResponseEndpointOut) SetData(v EndpointOut) {
	o.Data = v
}

func (o ResponseEndpointOut) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableResponseEndpointOut struct {
	value *ResponseEndpointOut
	isSet bool
}

func (v NullableResponseEndpointOut) Get() *ResponseEndpointOut {
	return v.value
}

func (v *NullableResponseEndpointOut) Set(val *ResponseEndpointOut) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseEndpointOut) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseEndpointOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseEndpointOut(val *ResponseEndpointOut) *NullableResponseEndpointOut {
	return &NullableResponseEndpointOut{value: val, isSet: true}
}

func (v NullableResponseEndpointOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseEndpointOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


