/*
 * WalletPay API Documentation
 *
 * This is a custody wallet pay service openapi server.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CursorPageCurrency struct for CursorPageCurrency
type CursorPageCurrency struct {
	// Whether there are more items available in the next page
	HasNext bool `json:"has_next"`
	// List of items in the current page
	Items []Currency `json:"items"`
	// Cursor for fetching the next page of items
	NextCursor *string `json:"next_cursor,omitempty"`
	// Cursor for fetching the previous page of items
	PrevCursor *string `json:"prev_cursor,omitempty"`
}

// NewCursorPageCurrency instantiates a new CursorPageCurrency object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCursorPageCurrency(hasNext bool, items []Currency) *CursorPageCurrency {
	this := CursorPageCurrency{}
	this.HasNext = hasNext
	this.Items = items
	return &this
}

// NewCursorPageCurrencyWithDefaults instantiates a new CursorPageCurrency object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCursorPageCurrencyWithDefaults() *CursorPageCurrency {
	this := CursorPageCurrency{}
	return &this
}

// GetHasNext returns the HasNext field value
func (o *CursorPageCurrency) GetHasNext() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasNext
}

// GetHasNextOk returns a tuple with the HasNext field value
// and a boolean to check if the value has been set.
func (o *CursorPageCurrency) GetHasNextOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.HasNext, true
}

// SetHasNext sets field value
func (o *CursorPageCurrency) SetHasNext(v bool) {
	o.HasNext = v
}

// GetItems returns the Items field value
func (o *CursorPageCurrency) GetItems() []Currency {
	if o == nil {
		var ret []Currency
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *CursorPageCurrency) GetItemsOk() (*[]Currency, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Items, true
}

// SetItems sets field value
func (o *CursorPageCurrency) SetItems(v []Currency) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *CursorPageCurrency) GetNextCursor() string {
	if o == nil || o.NextCursor == nil {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CursorPageCurrency) GetNextCursorOk() (*string, bool) {
	if o == nil || o.NextCursor == nil {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *CursorPageCurrency) HasNextCursor() bool {
	if o != nil && o.NextCursor != nil {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *CursorPageCurrency) SetNextCursor(v string) {
	o.NextCursor = &v
}

// GetPrevCursor returns the PrevCursor field value if set, zero value otherwise.
func (o *CursorPageCurrency) GetPrevCursor() string {
	if o == nil || o.PrevCursor == nil {
		var ret string
		return ret
	}
	return *o.PrevCursor
}

// GetPrevCursorOk returns a tuple with the PrevCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CursorPageCurrency) GetPrevCursorOk() (*string, bool) {
	if o == nil || o.PrevCursor == nil {
		return nil, false
	}
	return o.PrevCursor, true
}

// HasPrevCursor returns a boolean if a field has been set.
func (o *CursorPageCurrency) HasPrevCursor() bool {
	if o != nil && o.PrevCursor != nil {
		return true
	}

	return false
}

// SetPrevCursor gets a reference to the given string and assigns it to the PrevCursor field.
func (o *CursorPageCurrency) SetPrevCursor(v string) {
	o.PrevCursor = &v
}

func (o CursorPageCurrency) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["has_next"] = o.HasNext
	}
	if true {
		toSerialize["items"] = o.Items
	}
	if o.NextCursor != nil {
		toSerialize["next_cursor"] = o.NextCursor
	}
	if o.PrevCursor != nil {
		toSerialize["prev_cursor"] = o.PrevCursor
	}
	return json.Marshal(toSerialize)
}

type NullableCursorPageCurrency struct {
	value *CursorPageCurrency
	isSet bool
}

func (v NullableCursorPageCurrency) Get() *CursorPageCurrency {
	return v.value
}

func (v *NullableCursorPageCurrency) Set(val *CursorPageCurrency) {
	v.value = val
	v.isSet = true
}

func (v NullableCursorPageCurrency) IsSet() bool {
	return v.isSet
}

func (v *NullableCursorPageCurrency) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCursorPageCurrency(val *CursorPageCurrency) *NullableCursorPageCurrency {
	return &NullableCursorPageCurrency{value: val, isSet: true}
}

func (v NullableCursorPageCurrency) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCursorPageCurrency) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


