/*
 * WalletPay API Documentation
 *
 * This is a custody wallet pay service openapi server.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateEndpointRequest struct for CreateEndpointRequest
type CreateEndpointRequest struct {
	// The description of the endpoint
	Description *string `json:"description,omitempty"`
	// The disabled status of the endpoint
	Disabled *bool `json:"disabled,omitempty"`
	// The filter event types of the endpoint
	FilterTypes []string `json:"filter_types"`
	// The headers of the endpoint
	Headers map[string]string `json:"headers,omitempty"`
	// The metadata of the endpoint
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// The uid of the endpoint
	Uid *string `json:"uid,omitempty"`
	// The url of the endpoint
	Url string `json:"url"`
}

// NewCreateEndpointRequest instantiates a new CreateEndpointRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEndpointRequest(filterTypes []string, url string) *CreateEndpointRequest {
	this := CreateEndpointRequest{}
	this.FilterTypes = filterTypes
	this.Url = url
	return &this
}

// NewCreateEndpointRequestWithDefaults instantiates a new CreateEndpointRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEndpointRequestWithDefaults() *CreateEndpointRequest {
	this := CreateEndpointRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateEndpointRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEndpointRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateEndpointRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateEndpointRequest) SetDescription(v string) {
	o.Description = &v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *CreateEndpointRequest) GetDisabled() bool {
	if o == nil || o.Disabled == nil {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEndpointRequest) GetDisabledOk() (*bool, bool) {
	if o == nil || o.Disabled == nil {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *CreateEndpointRequest) HasDisabled() bool {
	if o != nil && o.Disabled != nil {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *CreateEndpointRequest) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetFilterTypes returns the FilterTypes field value
func (o *CreateEndpointRequest) GetFilterTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.FilterTypes
}

// GetFilterTypesOk returns a tuple with the FilterTypes field value
// and a boolean to check if the value has been set.
func (o *CreateEndpointRequest) GetFilterTypesOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FilterTypes, true
}

// SetFilterTypes sets field value
func (o *CreateEndpointRequest) SetFilterTypes(v []string) {
	o.FilterTypes = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateEndpointRequest) GetHeaders() map[string]string {
	if o == nil  {
		var ret map[string]string
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateEndpointRequest) GetHeadersOk() (*map[string]string, bool) {
	if o == nil || o.Headers == nil {
		return nil, false
	}
	return &o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *CreateEndpointRequest) HasHeaders() bool {
	if o != nil && o.Headers != nil {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *CreateEndpointRequest) SetHeaders(v map[string]string) {
	o.Headers = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateEndpointRequest) GetMetadata() map[string]interface{} {
	if o == nil  {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateEndpointRequest) GetMetadataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateEndpointRequest) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CreateEndpointRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *CreateEndpointRequest) GetUid() string {
	if o == nil || o.Uid == nil {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEndpointRequest) GetUidOk() (*string, bool) {
	if o == nil || o.Uid == nil {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *CreateEndpointRequest) HasUid() bool {
	if o != nil && o.Uid != nil {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *CreateEndpointRequest) SetUid(v string) {
	o.Uid = &v
}

// GetUrl returns the Url field value
func (o *CreateEndpointRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CreateEndpointRequest) GetUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CreateEndpointRequest) SetUrl(v string) {
	o.Url = v
}

func (o CreateEndpointRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Disabled != nil {
		toSerialize["disabled"] = o.Disabled
	}
	if true {
		toSerialize["filter_types"] = o.FilterTypes
	}
	if o.Headers != nil {
		toSerialize["headers"] = o.Headers
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Uid != nil {
		toSerialize["uid"] = o.Uid
	}
	if true {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

type NullableCreateEndpointRequest struct {
	value *CreateEndpointRequest
	isSet bool
}

func (v NullableCreateEndpointRequest) Get() *CreateEndpointRequest {
	return v.value
}

func (v *NullableCreateEndpointRequest) Set(val *CreateEndpointRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEndpointRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEndpointRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEndpointRequest(val *CreateEndpointRequest) *NullableCreateEndpointRequest {
	return &NullableCreateEndpointRequest{value: val, isSet: true}
}

func (v NullableCreateEndpointRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEndpointRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


