/*
 * Wallet-Pay API Documentations
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ResponseListEndpointOut struct for ResponseListEndpointOut
type ResponseListEndpointOut struct {
	Data ListResponseEndpointOut `json:"data"`
}

// NewResponseListEndpointOut instantiates a new ResponseListEndpointOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseListEndpointOut(data ListResponseEndpointOut) *ResponseListEndpointOut {
	this := ResponseListEndpointOut{}
	this.Data = data
	return &this
}

// NewResponseListEndpointOutWithDefaults instantiates a new ResponseListEndpointOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseListEndpointOutWithDefaults() *ResponseListEndpointOut {
	this := ResponseListEndpointOut{}
	return &this
}

// GetData returns the Data field value
func (o *ResponseListEndpointOut) GetData() ListResponseEndpointOut {
	if o == nil {
		var ret ListResponseEndpointOut
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResponseListEndpointOut) GetDataOk() (*ListResponseEndpointOut, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ResponseListEndpointOut) SetData(v ListResponseEndpointOut) {
	o.Data = v
}

func (o ResponseListEndpointOut) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableResponseListEndpointOut struct {
	value *ResponseListEndpointOut
	isSet bool
}

func (v NullableResponseListEndpointOut) Get() *ResponseListEndpointOut {
	return v.value
}

func (v *NullableResponseListEndpointOut) Set(val *ResponseListEndpointOut) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseListEndpointOut) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseListEndpointOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseListEndpointOut(val *ResponseListEndpointOut) *NullableResponseListEndpointOut {
	return &NullableResponseListEndpointOut{value: val, isSet: true}
}

func (v NullableResponseListEndpointOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseListEndpointOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


