/*
 * Wallet-Pay API Documentations
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RefundIn struct for RefundIn
type RefundIn struct {
	// Optional unique identifier for the refund
	Uid *string `json:"uid,omitempty"`
	// The order's ID
	OrderId string `json:"order_id"`
	// Big integer string representation, whose meaning is the value of absolute floating-point number multiplied by the corresponding decimals of the cryptocurrency.
	Amount string `json:"amount"`
	// Optional refund note
	Note *string `json:"note,omitempty"`
}

// NewRefundIn instantiates a new RefundIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefundIn(orderId string, amount string) *RefundIn {
	this := RefundIn{}
	this.OrderId = orderId
	this.Amount = amount
	return &this
}

// NewRefundInWithDefaults instantiates a new RefundIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefundInWithDefaults() *RefundIn {
	this := RefundIn{}
	return &this
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *RefundIn) GetUid() string {
	if o == nil || o.Uid == nil {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundIn) GetUidOk() (*string, bool) {
	if o == nil || o.Uid == nil {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *RefundIn) HasUid() bool {
	if o != nil && o.Uid != nil {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *RefundIn) SetUid(v string) {
	o.Uid = &v
}

// GetOrderId returns the OrderId field value
func (o *RefundIn) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *RefundIn) GetOrderIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *RefundIn) SetOrderId(v string) {
	o.OrderId = v
}

// GetAmount returns the Amount field value
func (o *RefundIn) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *RefundIn) GetAmountOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *RefundIn) SetAmount(v string) {
	o.Amount = v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *RefundIn) GetNote() string {
	if o == nil || o.Note == nil {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RefundIn) GetNoteOk() (*string, bool) {
	if o == nil || o.Note == nil {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *RefundIn) HasNote() bool {
	if o != nil && o.Note != nil {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *RefundIn) SetNote(v string) {
	o.Note = &v
}

func (o RefundIn) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Uid != nil {
		toSerialize["uid"] = o.Uid
	}
	if true {
		toSerialize["order_id"] = o.OrderId
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if o.Note != nil {
		toSerialize["note"] = o.Note
	}
	return json.Marshal(toSerialize)
}

type NullableRefundIn struct {
	value *RefundIn
	isSet bool
}

func (v NullableRefundIn) Get() *RefundIn {
	return v.value
}

func (v *NullableRefundIn) Set(val *RefundIn) {
	v.value = val
	v.isSet = true
}

func (v NullableRefundIn) IsSet() bool {
	return v.isSet
}

func (v *NullableRefundIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefundIn(val *RefundIn) *NullableRefundIn {
	return &NullableRefundIn{value: val, isSet: true}
}

func (v NullableRefundIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefundIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


