/*
 * Wallet-Pay API Documentations
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetRatesOut struct for GetRatesOut
type GetRatesOut struct {
	Data Rates `json:"data"`
}

// NewGetRatesOut instantiates a new GetRatesOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRatesOut(data Rates) *GetRatesOut {
	this := GetRatesOut{}
	this.Data = data
	return &this
}

// NewGetRatesOutWithDefaults instantiates a new GetRatesOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRatesOutWithDefaults() *GetRatesOut {
	this := GetRatesOut{}
	return &this
}

// GetData returns the Data field value
func (o *GetRatesOut) GetData() Rates {
	if o == nil {
		var ret Rates
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetRatesOut) GetDataOk() (*Rates, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetRatesOut) SetData(v Rates) {
	o.Data = v
}

func (o GetRatesOut) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableGetRatesOut struct {
	value *GetRatesOut
	isSet bool
}

func (v NullableGetRatesOut) Get() *GetRatesOut {
	return v.value
}

func (v *NullableGetRatesOut) Set(val *GetRatesOut) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRatesOut) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRatesOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRatesOut(val *GetRatesOut) *NullableGetRatesOut {
	return &NullableGetRatesOut{value: val, isSet: true}
}

func (v NullableGetRatesOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRatesOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


