/*
 * Wallet-Pay API Documentations
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ResponseCurrencyOut struct for ResponseCurrencyOut
type ResponseCurrencyOut struct {
	Data CurrencyOut `json:"data"`
}

// NewResponseCurrencyOut instantiates a new ResponseCurrencyOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseCurrencyOut(data CurrencyOut) *ResponseCurrencyOut {
	this := ResponseCurrencyOut{}
	this.Data = data
	return &this
}

// NewResponseCurrencyOutWithDefaults instantiates a new ResponseCurrencyOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseCurrencyOutWithDefaults() *ResponseCurrencyOut {
	this := ResponseCurrencyOut{}
	return &this
}

// GetData returns the Data field value
func (o *ResponseCurrencyOut) GetData() CurrencyOut {
	if o == nil {
		var ret CurrencyOut
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResponseCurrencyOut) GetDataOk() (*CurrencyOut, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ResponseCurrencyOut) SetData(v CurrencyOut) {
	o.Data = v
}

func (o ResponseCurrencyOut) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableResponseCurrencyOut struct {
	value *ResponseCurrencyOut
	isSet bool
}

func (v NullableResponseCurrencyOut) Get() *ResponseCurrencyOut {
	return v.value
}

func (v *NullableResponseCurrencyOut) Set(val *ResponseCurrencyOut) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseCurrencyOut) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseCurrencyOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseCurrencyOut(val *ResponseCurrencyOut) *NullableResponseCurrencyOut {
	return &NullableResponseCurrencyOut{value: val, isSet: true}
}

func (v NullableResponseCurrencyOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseCurrencyOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


