/*
 * WalletPay API Documentation
 *
 * This is a custody wallet pay service openapi server.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EstimateResponse struct for EstimateResponse
type EstimateResponse struct {
	// Amount in source currency
	BaseAmount string `json:"base_amount"`
	// Source currency code
	BaseCurrency string `json:"base_currency"`
	// Exchange rate used for conversion
	Rate float32 `json:"rate"`
	// Converted amount in target currency
	ToAmount string `json:"to_amount"`
	// Target currency code
	ToCurrency string `json:"to_currency"`
}

// NewEstimateResponse instantiates a new EstimateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEstimateResponse(baseAmount string, baseCurrency string, rate float32, toAmount string, toCurrency string) *EstimateResponse {
	this := EstimateResponse{}
	this.BaseAmount = baseAmount
	this.BaseCurrency = baseCurrency
	this.Rate = rate
	this.ToAmount = toAmount
	this.ToCurrency = toCurrency
	return &this
}

// NewEstimateResponseWithDefaults instantiates a new EstimateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEstimateResponseWithDefaults() *EstimateResponse {
	this := EstimateResponse{}
	return &this
}

// GetBaseAmount returns the BaseAmount field value
func (o *EstimateResponse) GetBaseAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseAmount
}

// GetBaseAmountOk returns a tuple with the BaseAmount field value
// and a boolean to check if the value has been set.
func (o *EstimateResponse) GetBaseAmountOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BaseAmount, true
}

// SetBaseAmount sets field value
func (o *EstimateResponse) SetBaseAmount(v string) {
	o.BaseAmount = v
}

// GetBaseCurrency returns the BaseCurrency field value
func (o *EstimateResponse) GetBaseCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseCurrency
}

// GetBaseCurrencyOk returns a tuple with the BaseCurrency field value
// and a boolean to check if the value has been set.
func (o *EstimateResponse) GetBaseCurrencyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BaseCurrency, true
}

// SetBaseCurrency sets field value
func (o *EstimateResponse) SetBaseCurrency(v string) {
	o.BaseCurrency = v
}

// GetRate returns the Rate field value
func (o *EstimateResponse) GetRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Rate
}

// GetRateOk returns a tuple with the Rate field value
// and a boolean to check if the value has been set.
func (o *EstimateResponse) GetRateOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Rate, true
}

// SetRate sets field value
func (o *EstimateResponse) SetRate(v float32) {
	o.Rate = v
}

// GetToAmount returns the ToAmount field value
func (o *EstimateResponse) GetToAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToAmount
}

// GetToAmountOk returns a tuple with the ToAmount field value
// and a boolean to check if the value has been set.
func (o *EstimateResponse) GetToAmountOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ToAmount, true
}

// SetToAmount sets field value
func (o *EstimateResponse) SetToAmount(v string) {
	o.ToAmount = v
}

// GetToCurrency returns the ToCurrency field value
func (o *EstimateResponse) GetToCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToCurrency
}

// GetToCurrencyOk returns a tuple with the ToCurrency field value
// and a boolean to check if the value has been set.
func (o *EstimateResponse) GetToCurrencyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ToCurrency, true
}

// SetToCurrency sets field value
func (o *EstimateResponse) SetToCurrency(v string) {
	o.ToCurrency = v
}

func (o EstimateResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["base_amount"] = o.BaseAmount
	}
	if true {
		toSerialize["base_currency"] = o.BaseCurrency
	}
	if true {
		toSerialize["rate"] = o.Rate
	}
	if true {
		toSerialize["to_amount"] = o.ToAmount
	}
	if true {
		toSerialize["to_currency"] = o.ToCurrency
	}
	return json.Marshal(toSerialize)
}

type NullableEstimateResponse struct {
	value *EstimateResponse
	isSet bool
}

func (v NullableEstimateResponse) Get() *EstimateResponse {
	return v.value
}

func (v *NullableEstimateResponse) Set(val *EstimateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEstimateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEstimateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEstimateResponse(val *EstimateResponse) *NullableEstimateResponse {
	return &NullableEstimateResponse{value: val, isSet: true}
}

func (v NullableEstimateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEstimateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


