/*
 * WalletPay API Documentation
 *
 * This is a custody wallet pay service openapi server.
 *
 * API version: 1.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// TransferRequest struct for TransferRequest
type TransferRequest struct {
	// Amount to transfer, supports decimal values
	Amount string `json:"amount"`
	// Whether to automatically commit the transfer
	AutoCommit *bool `json:"auto_commit,omitempty"`
	// Currency code for the transfer (e.g., TON, USDT, ETH)
	Currency string `json:"currency"`
	// Optional description for the transfer
	Description *string `json:"description,omitempty"`
	// Optional tags for categorizing the transfer
	Tags []string `json:"tags,omitempty"`
	// Destination wallet ID to transfer funds to
	ToWalletId string `json:"to_wallet_id"`
}

// NewTransferRequest instantiates a new TransferRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferRequest(amount string, currency string, toWalletId string) *TransferRequest {
	this := TransferRequest{}
	this.Amount = amount
	this.Currency = currency
	this.ToWalletId = toWalletId
	return &this
}

// NewTransferRequestWithDefaults instantiates a new TransferRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferRequestWithDefaults() *TransferRequest {
	this := TransferRequest{}
	return &this
}

// GetAmount returns the Amount field value
func (o *TransferRequest) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *TransferRequest) GetAmountOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *TransferRequest) SetAmount(v string) {
	o.Amount = v
}

// GetAutoCommit returns the AutoCommit field value if set, zero value otherwise.
func (o *TransferRequest) GetAutoCommit() bool {
	if o == nil || o.AutoCommit == nil {
		var ret bool
		return ret
	}
	return *o.AutoCommit
}

// GetAutoCommitOk returns a tuple with the AutoCommit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferRequest) GetAutoCommitOk() (*bool, bool) {
	if o == nil || o.AutoCommit == nil {
		return nil, false
	}
	return o.AutoCommit, true
}

// HasAutoCommit returns a boolean if a field has been set.
func (o *TransferRequest) HasAutoCommit() bool {
	if o != nil && o.AutoCommit != nil {
		return true
	}

	return false
}

// SetAutoCommit gets a reference to the given bool and assigns it to the AutoCommit field.
func (o *TransferRequest) SetAutoCommit(v bool) {
	o.AutoCommit = &v
}

// GetCurrency returns the Currency field value
func (o *TransferRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *TransferRequest) GetCurrencyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *TransferRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TransferRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransferRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TransferRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TransferRequest) SetDescription(v string) {
	o.Description = &v
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TransferRequest) GetTags() []string {
	if o == nil  {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TransferRequest) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return &o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *TransferRequest) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *TransferRequest) SetTags(v []string) {
	o.Tags = v
}

// GetToWalletId returns the ToWalletId field value
func (o *TransferRequest) GetToWalletId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToWalletId
}

// GetToWalletIdOk returns a tuple with the ToWalletId field value
// and a boolean to check if the value has been set.
func (o *TransferRequest) GetToWalletIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ToWalletId, true
}

// SetToWalletId sets field value
func (o *TransferRequest) SetToWalletId(v string) {
	o.ToWalletId = v
}

func (o TransferRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["amount"] = o.Amount
	}
	if o.AutoCommit != nil {
		toSerialize["auto_commit"] = o.AutoCommit
	}
	if true {
		toSerialize["currency"] = o.Currency
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if true {
		toSerialize["to_wallet_id"] = o.ToWalletId
	}
	return json.Marshal(toSerialize)
}

type NullableTransferRequest struct {
	value *TransferRequest
	isSet bool
}

func (v NullableTransferRequest) Get() *TransferRequest {
	return v.value
}

func (v *NullableTransferRequest) Set(val *TransferRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferRequest(val *TransferRequest) *NullableTransferRequest {
	return &NullableTransferRequest{value: val, isSet: true}
}

func (v NullableTransferRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


