/**
 * WalletPay API Documentation
 * This is a custody wallet pay service openapi server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateOrderRequest {
    /**
    * Amount, supports decimal values
    */
    'amount': string;
    /**
    * The identifier of the user who created the order
    */
    'creator'?: string;
    /**
    * Currency code. e.g.: USDT, TON, ETH
    */
    'currency': string;
    /**
    * Expiration time in seconds. If payment is not completed within the given time, the order will be automatically canceled
    */
    'expiration'?: number;
    /**
    * Order metadata
    */
    'metadata'?: { [key: string]: string; };
    /**
    * Order description from merchant
    */
    'note'?: string;
    /**
    * External ID, the order ID in the merchant system
    */
    'uid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "creator",
            "baseName": "creator",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiration",
            "baseName": "expiration",
            "type": "number",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateOrderRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

