/**
 * Wallet-Pay API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EstimateData {
    /**
    * The base currency.
    */
    'from': string;
    /**
    * The base currency amount.
    */
    'baseAmount': number;
    /**
    * The target currency
    */
    'toCurrency': string;
    /**
    * The estimated amount in the target currency
    */
    'toAmount': number;
    /**
    * The conversion rate from the base currency to the target currency.
    */
    'rate': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "from",
            "baseName": "from",
            "type": "string",
            "format": ""
        },
        {
            "name": "baseAmount",
            "baseName": "base_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "toCurrency",
            "baseName": "to_currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAmount",
            "baseName": "to_amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EstimateData.attributeTypeMap;
    }
    
    public constructor() {
    }
}

