/**
 * WalletPay API Documentation
 * This is a custody wallet pay service openapi server.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Rate } from './Rate';
import { HttpFile } from '../http/http';

export class GetRatesResponse {
    /**
    * List of exchange rates for requested currency pairs
    */
    'rates': Array<Rate>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "rates",
            "baseName": "rates",
            "type": "Array<Rate>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetRatesResponse.attributeTypeMap;
    }
    
    public constructor() {
    }
}

