/**
 * Wallet-Pay API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RefundOut {
    /**
    * The refund's ID
    */
    'id': string;
    /**
    * The refund's UID
    */
    'uid'?: string;
    /**
    * The relative order id
    */
    'orderId': string;
    /**
    * Currency code
    */
    'currency': string;
    /**
    * Big integer string representation, whose meaning is the value of absolute floating-point number multiplied by the corresponding decimals of the cryptocurrency.
    */
    'amount': string;
    /**
    * The refund's status
    */
    'status': RefundOutStatusEnum;
    /**
    * Optional refund note
    */
    'note'?: string;
    /**
    * The refund's failure time
    */
    'failedAt'?: Date;
    /**
    * The message when refund failed
    */
    'failedMessage'?: string;
    /**
    * The refund's created time
    */
    'createdAt': Date;
    /**
    * The refund's completed time
    */
    'completedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "uid",
            "baseName": "uid",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "RefundOutStatusEnum",
            "format": ""
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string",
            "format": ""
        },
        {
            "name": "failedAt",
            "baseName": "failed_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "failedMessage",
            "baseName": "failed_message",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "completedAt",
            "baseName": "completed_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return RefundOut.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type RefundOutStatusEnum = "PENDING" | "FAILED" | "COMPLETED" ;

