/**
 * Wallet-Pay API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TransferOut } from './TransferOut';
import { HttpFile } from '../http/http';

export class ResponseTransferOut {
    'data': TransferOut;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "TransferOut",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResponseTransferOut.attributeTypeMap;
    }
    
    public constructor() {
    }
}

