/*
 * Wallet-Pay API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.walletpay.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CurrencyOut
 */
public class CurrencyOutTest {
    private final CurrencyOut model = new CurrencyOut();

    /**
     * Model tests for CurrencyOut
     */
    @Test
    public void testCurrencyOut() {
        // TODO: test CurrencyOut
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'logo'
     */
    @Test
    public void logoTest() {
        // TODO: test logo
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'canDeposit'
     */
    @Test
    public void canDepositTest() {
        // TODO: test canDeposit
    }

    /**
     * Test the property 'canWithdraw'
     */
    @Test
    public void canWithdrawTest() {
        // TODO: test canWithdraw
    }

    /**
     * Test the property 'canTransfer'
     */
    @Test
    public void canTransferTest() {
        // TODO: test canTransfer
    }

    /**
     * Test the property 'minDepositAmount'
     */
    @Test
    public void minDepositAmountTest() {
        // TODO: test minDepositAmount
    }

    /**
     * Test the property 'minWithdrawAmount'
     */
    @Test
    public void minWithdrawAmountTest() {
        // TODO: test minWithdrawAmount
    }

    /**
     * Test the property 'maxWithdrawAmount'
     */
    @Test
    public void maxWithdrawAmountTest() {
        // TODO: test maxWithdrawAmount
    }

    /**
     * Test the property 'precision'
     */
    @Test
    public void precisionTest() {
        // TODO: test precision
    }

    /**
     * Test the property 'decimals'
     */
    @Test
    public void decimalsTest() {
        // TODO: test decimals
    }

}
