/*
 * WalletPay API Documentation
 * This is a custody wallet pay service openapi server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.walletpay.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openweb3.walletpay.models.Endpoint;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CursorPageEndpoint
 */
public class CursorPageEndpointTest {
    private final CursorPageEndpoint model = new CursorPageEndpoint();

    /**
     * Model tests for CursorPageEndpoint
     */
    @Test
    public void testCursorPageEndpoint() {
        // TODO: test CursorPageEndpoint
    }

    /**
     * Test the property 'hasNext'
     */
    @Test
    public void hasNextTest() {
        // TODO: test hasNext
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'nextCursor'
     */
    @Test
    public void nextCursorTest() {
        // TODO: test nextCursor
    }

    /**
     * Test the property 'prevCursor'
     */
    @Test
    public void prevCursorTest() {
        // TODO: test prevCursor
    }

}
