/*
 * WalletPay API Documentation
 * This is a custody wallet pay service openapi server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.walletpay.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EstimateResponse
 */
public class EstimateResponseTest {
    private final EstimateResponse model = new EstimateResponse();

    /**
     * Model tests for EstimateResponse
     */
    @Test
    public void testEstimateResponse() {
        // TODO: test EstimateResponse
    }

    /**
     * Test the property 'baseAmount'
     */
    @Test
    public void baseAmountTest() {
        // TODO: test baseAmount
    }

    /**
     * Test the property 'baseCurrency'
     */
    @Test
    public void baseCurrencyTest() {
        // TODO: test baseCurrency
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'toAmount'
     */
    @Test
    public void toAmountTest() {
        // TODO: test toAmount
    }

    /**
     * Test the property 'toCurrency'
     */
    @Test
    public void toCurrencyTest() {
        // TODO: test toCurrency
    }

}
