/*
 * Wallet-Pay API Documentations
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.openweb3.walletpay.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ResponseRateEstimateOut
 */
public class ResponseRateEstimateOutTest {
    private final ResponseRateEstimateOut model = new ResponseRateEstimateOut();

    /**
     * Model tests for ResponseRateEstimateOut
     */
    @Test
    public void testResponseRateEstimateOut() {
        // TODO: test ResponseRateEstimateOut
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'baseAmount'
     */
    @Test
    public void baseAmountTest() {
        // TODO: test baseAmount
    }

    /**
     * Test the property 'toCurrency'
     */
    @Test
    public void toCurrencyTest() {
        // TODO: test toCurrency
    }

    /**
     * Test the property 'toAmount'
     */
    @Test
    public void toAmountTest() {
        // TODO: test toAmount
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

}
